musteriAd=input("İsminiz: ")
musteriSoyad=input("Soyadınız: ")
musteriTelNo=input("Telefon Numaranız: ")

urun1Ad=input("Aldığınız Ürün: ")
urunFiyat=input("Fiyatı: ")
print("-----Ürünü alan kişi:----- ")
print(musteriAd)
print(musteriSoyad)
print(musteriTelNo)
print("-----aldığı ürünler: -----")
print(urun1Ad)
print(urunFiyat)
print(urun1Ad+urunFiyat)